version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 742231939429.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - export SEMVER_VERSION=$(date +'%Y.%m.%d')-$(printf %06d $CODEBUILD_BUILD_NUMBER)
      - docker build -t test-repo ./images
      - docker tag test-repo:latest 742231939429.dkr.ecr.us-east-1.amazonaws.com/test-repo:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 742231939429.dkr.ecr.us-east-1.amazonaws.com/test-repo:latest
      - echo Image pushed successfully to Amazon ECR 
