version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 742231939429.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - export PREVIOUS_VERSION=$(git describe --tags --abbrev=0)
      - export MAJOR_VERSION=$(echo $PREVIOUS_VERSION | awk -F. '{print $1}' | sed 's/v//')
      - export MINOR_VERSION=$(echo $PREVIOUS_VERSION | awk -F. '{print $2}')
      - export PATCH_VERSION=$(echo $PREVIOUS_VERSION | awk -F. '{print $3}')
      - export NEW_VERSION="v${MAJOR_VERSION}.${MINOR_VERSION}.$(($PATCH_VERSION+1))"
      - docker build -t test-repo:$NEW_VERSION ./images
      - docker tag test-repo:$NEW_VERSION 742231939429.dkr.ecr.us-east-1.amazonaws.com/test-repo:$NEW_VERSION
      - docker tag test-repo:$NEW_VERSION 742231939429.dkr.ecr.us-east-1.amazonaws.com/test-repo:latest

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 742231939429.dkr.ecr.us-east-1.amazonaws.com/test-repo:$NEW_VERSION
      - docker push 742231939429.dkr.ecr.us-east-1.amazonaws.com/test-repo:latest
      - echo Image pushed successfully to Amazon ECR
